version: '3.8'

services:

  # 🔧 DEV MODE (auto reload)
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    container_name: angular-dev

  # 🚀 PROD MODE (nginx)
  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: angular-prod